#!/usr/bin/env python3
"""Rebuilds the upstream Immich compose file for this server:
- removes the immich-machine-learning service (runs on a separate Pi)
- removes the model-cache volume
- adds the read-only external library mount
- caps Postgres shared_buffers (image default 512MB is oversized here)

Usage: transform-compose.py <upstream.yml> <target.yml>

Running everything on a single Pi instead? Delete the ML-removal block
below and keep the service in your compose file.
"""
import sys
import yaml

# ---- adjust to your setup -------------------------------------------------
EXTERNAL_LIB = "/srv/photo-archive:/mnt/photos:ro"
SHARED_BUFFERS = "256MB"
ML_PI = "192.168.0.11:3003"  # only used in the generated header comment
# ---------------------------------------------------------------------------

HEADER = (
    "# NOTE: This file is generated by update-server.sh from the upstream\n"
    "# template (docker-compose.yml.upstream). Keep local changes in\n"
    "# transform-compose.py, not here!\n"
    f"# ML runs on a separate Pi ({ML_PI}).\n"
)

src, dst = sys.argv[1], sys.argv[2]
with open(src) as f:
    doc = yaml.safe_load(f)

services = doc.get("services", {})

if "immich-machine-learning" in services:
    del services["immich-machine-learning"]
else:
    print("WARNING: upstream compose has no immich-machine-learning service"
          " anymore - check manually!", file=sys.stderr)

volumes = doc.get("volumes")
if volumes and "model-cache" in volumes:
    del volumes["model-cache"]
    if not volumes:
        del doc["volumes"]

server = services.get("immich-server")
if server is None:
    sys.exit("ERROR: no immich-server service in the upstream file")
vols = server.setdefault("volumes", [])
if EXTERNAL_LIB not in vols:
    vols.append(EXTERNAL_LIB)

# Postgres RAM cap: append to the existing command. If the image ever ships
# a different default CMD, update the fallback here (docker inspect .Config.Cmd).
db = services.get("database")
if db is not None:
    cmd = db.get("command")
    if not isinstance(cmd, list) or not cmd:
        cmd = ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    if not any("shared_buffers" in str(part) for part in cmd):
        cmd = cmd + ["-c", f"shared_buffers={SHARED_BUFFERS}"]
    db["command"] = cmd
else:
    print("WARNING: no database service found - shared_buffers not set",
          file=sys.stderr)

with open(dst, "w") as f:
    f.write(HEADER)
    yaml.safe_dump(doc, f, sort_keys=False, allow_unicode=True)

print(f"OK: {dst} generated (ML service removed, external library added)")
